"""create initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-03 15:19:52.713948
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from backend.app.models.base import UTCDateTime, UUIDString


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('wechat_openid', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    op.create_table('identification_tags',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index(op.f('ix_identification_tags_user_id'), 'identification_tags', ['user_id'], unique=False)
    op.create_index(op.f('ix_identification_tags_uuid'), 'identification_tags', ['uuid'], unique=True)
    op.create_table('management_unit_types',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index(op.f('ix_management_unit_types_user_id'), 'management_unit_types', ['user_id'], unique=False)
    op.create_index(op.f('ix_management_unit_types_uuid'), 'management_unit_types', ['uuid'], unique=True)
    op.create_table('personal_genes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phenotype', sa.String(length=255), nullable=True),
    sa.Column('genotype', sa.String(length=255), nullable=True),
    sa.Column('inheritance_mode', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index(op.f('ix_personal_genes_user_id'), 'personal_genes', ['user_id'], unique=False)
    op.create_index(op.f('ix_personal_genes_uuid'), 'personal_genes', ['uuid'], unique=True)
    op.create_table('personal_species',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('kingdom', sa.String(length=255), nullable=True),
    sa.Column('phylum', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('order_name', sa.String(length=255), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('genus', sa.String(length=255), nullable=True),
    sa.Column('species_name', sa.String(length=255), nullable=True),
    sa.Column('subspecies', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'common_name')
    )
    op.create_index(op.f('ix_personal_species_user_id'), 'personal_species', ['user_id'], unique=False)
    op.create_index(op.f('ix_personal_species_uuid'), 'personal_species', ['uuid'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=False),
    sa.Column('revoked_at', UTCDateTime(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_uuid'), 'refresh_tokens', ['uuid'], unique=True)
    op.create_table('management_units',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['management_unit_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_code')
    )
    op.create_index(op.f('ix_management_units_user_id'), 'management_units', ['user_id'], unique=False)
    op.create_index(op.f('ix_management_units_uuid'), 'management_units', ['uuid'], unique=True)
    op.create_table('pets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('pet_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=False),
    sa.Column('identification_note', sa.String(length=1000), nullable=True),
    sa.Column('owner_note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['personal_species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pet_code')
    )
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_index(op.f('ix_pets_uuid'), 'pets', ['uuid'], unique=True)
    op.create_table('pet_genes',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['personal_genes.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'gene_id')
    )
    op.create_index(op.f('ix_pet_genes_uuid'), 'pet_genes', ['uuid'], unique=True)
    op.create_table('pet_identification_tags',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['identification_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'tag_id')
    )
    op.create_index(op.f('ix_pet_identification_tags_uuid'), 'pet_identification_tags', ['uuid'], unique=True)
    op.create_table('pet_life_stages',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('ended_at', UTCDateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_life_stages_pet_id'), 'pet_life_stages', ['pet_id'], unique=False)
    op.create_index(op.f('ix_pet_life_stages_uuid'), 'pet_life_stages', ['uuid'], unique=True)
    op.create_table('pet_management_assignments',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('management_unit_id', sa.Integer(), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('ended_at', UTCDateTime(), nullable=True),
    sa.Column('life_stage', sa.String(length=255), nullable=True),
    sa.Column('transfer_reason', sa.String(length=1000), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['management_unit_id'], ['management_units.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_management_assignments_management_unit_id'), 'pet_management_assignments', ['management_unit_id'], unique=False)
    op.create_index(op.f('ix_pet_management_assignments_pet_id'), 'pet_management_assignments', ['pet_id'], unique=False)
    op.create_index(op.f('ix_pet_management_assignments_uuid'), 'pet_management_assignments', ['uuid'], unique=True)
    op.create_table('pet_origins',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('origin_type', sa.String(length=32), nullable=False),
    sa.Column('parent_role', sa.String(length=32), nullable=False),
    sa.Column('parent_pet_id', sa.Integer(), nullable=True),
    sa.Column('breeder_name', sa.String(length=255), nullable=True),
    sa.Column('external_name', sa.String(length=255), nullable=True),
    sa.Column('genetic_note', sa.String(length=1000), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', UUIDString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_origins_pet_id'), 'pet_origins', ['pet_id'], unique=False)
    op.create_index(op.f('ix_pet_origins_uuid'), 'pet_origins', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_origins_uuid'), table_name='pet_origins')
    op.drop_index(op.f('ix_pet_origins_pet_id'), table_name='pet_origins')
    op.drop_table('pet_origins')
    op.drop_index(op.f('ix_pet_management_assignments_uuid'), table_name='pet_management_assignments')
    op.drop_index(op.f('ix_pet_management_assignments_pet_id'), table_name='pet_management_assignments')
    op.drop_index(op.f('ix_pet_management_assignments_management_unit_id'), table_name='pet_management_assignments')
    op.drop_table('pet_management_assignments')
    op.drop_index(op.f('ix_pet_life_stages_uuid'), table_name='pet_life_stages')
    op.drop_index(op.f('ix_pet_life_stages_pet_id'), table_name='pet_life_stages')
    op.drop_table('pet_life_stages')
    op.drop_index(op.f('ix_pet_identification_tags_uuid'), table_name='pet_identification_tags')
    op.drop_table('pet_identification_tags')
    op.drop_index(op.f('ix_pet_genes_uuid'), table_name='pet_genes')
    op.drop_table('pet_genes')
    op.drop_index(op.f('ix_pets_uuid'), table_name='pets')
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_management_units_uuid'), table_name='management_units')
    op.drop_index(op.f('ix_management_units_user_id'), table_name='management_units')
    op.drop_table('management_units')
    op.drop_index(op.f('ix_refresh_tokens_uuid'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_personal_species_uuid'), table_name='personal_species')
    op.drop_index(op.f('ix_personal_species_user_id'), table_name='personal_species')
    op.drop_table('personal_species')
    op.drop_index(op.f('ix_personal_genes_uuid'), table_name='personal_genes')
    op.drop_index(op.f('ix_personal_genes_user_id'), table_name='personal_genes')
    op.drop_table('personal_genes')
    op.drop_index(op.f('ix_management_unit_types_uuid'), table_name='management_unit_types')
    op.drop_index(op.f('ix_management_unit_types_user_id'), table_name='management_unit_types')
    op.drop_table('management_unit_types')
    op.drop_index(op.f('ix_identification_tags_uuid'), table_name='identification_tags')
    op.drop_index(op.f('ix_identification_tags_user_id'), table_name='identification_tags')
    op.drop_table('identification_tags')
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
